<?php
    $columnsLimit = $block->getColumnsLimit() ?: 0;
    $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit);
    $currentUrl = $block->getCurrentUrl();
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
?>

<nav class="navigation" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
    <li class="level0 <?php if($currentUrl == '/'): ?>active<?php endif; ?>"><a href="<?php echo $storeManager->getStore()->getBaseUrl(); ?>"  title="<?php echo __('Home') ?>" class="level-top">   
    <i class="fas fa-home"></i>
    <span>Home</span></a></li>  
    <?php echo $_menu; ?>
    <li class="level0 <?php if($currentUrl == '/defabrica'): ?>active<?php endif; ?>"><a href="<?php echo $storeManager->getStore()->getBaseUrl(); ?>"  title="<?php echo __('DeFabrica') ?>" class="level-top">   
    <span>¿Qué es defabrica.com?</span></a></li>  
    <?php echo $_menu; ?>
    <li class="level0 <?php if($currentUrl == '/empresas'): ?>active<?php endif; ?>"><a href="<?php echo $storeManager->getStore()->getBaseUrl(); ?>"  title="<?php echo __('Empresas') ?>" class="level-top">   
    <span>Empresas</span></a></li>  
    <?php echo $_menu; ?>
    <li class="level0 <?php if($currentUrl == '/contacto'): ?>active<?php endif; ?>"><a href="<?php echo $storeManager->getStore()->getBaseUrl(); ?>"  title="<?php echo __('Contacto') ?>" class="level-top">   
    <i class="far fa-envelope"></i>
    <span>Contacto</span></a></li>  
    <?php echo $_menu; ?>
    </ul>
</nav>